// Assignment code here
var lowerCase = [
  "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"
];
var upperCase = [
  "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"
];
var numberical = [
  "1", "2", "3", "4", "5", "6", "7", "8", "9"
];
var specialCharacters = [
  "!", "#", "$", "%", "&", "(", ")", "*", "+", ",", "-", ".", "/", ":", ";", "<", "=", ">", "?", "@", "[", "^", "_", "`", "{", "|", "}", "~"
];


// Get references to the #generate element
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = generatePassword(); //generatePassword()
  var passwordText = document.querySelector("#password");
  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
 

//functions 
function checkLength() {
var passLength = prompt("How many character would you like your password to be? (must be within 8 and 128) ");
//while loops will run until correct
if (passLength < 8 || passLength > 128) {
  alert("password characters must be between 8 and 128");
  return null;
}

//if (passLength >= 8 && passLength <= 128) {
  //generatePassword();
//}

  var lowPass = confirm("would you like lowercase characters in your password?");
  var uppPass = confirm("would you like upper case characters in your password?");
  var numPass = confirm("would you like numerical characters in your password?");
  var specPass = confirm("would you like special characters in your password?");
  //min var will contain the random letters/numbers/specialcharacters generated by the functions 

    if (!lowPass && !uppPass && !numPass && !specPass) {
      alert("must select atleast one"); 
      return null
  } 
  var inputCriteria = {
    passLength: passLength,
    lowPass: lowPass,
    numPass: numPass,
    specPass: specPass
  }
  return inputCriteria;
}

function generatePassword(){
  var criteria = inputCriteria(); 
    
     

}