// Assignment code here


// Get references to the #generate element
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = checkLength(); //generatePassword()
  var passwordText = document.querySelector("#password");
  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);
 

//functions 
function checkLength() {
var passLength = prompt("How many character would you like your password to be? (must be within 8 and 128) ");
if (passLength < 8 || passLength > 128) {
  alert("password characters must be between 8 and 128");
  return;
}
else if (passLength >= 8 && passLength <= 128) {
  generatePassword();
}
}

function generatePassword(){
  var lowPass = confirm("would you like lowercase characters in your password?");
  var uppPass = confirm("would you like upper case characters in your password?");
  var numPass = confirm("would you like numerical characters in your password?");
  var specPass = confirm("would you like special characters in your password?");
  //min var will contain the random letters/numbers/specialcharacters generated by the functions 
  var min = 0;

    if (!lowPass && !uppPass && !numPass && !specPass) {
      alert("must select atleast one"); 
      generatePassword();
  } 
    
     

  var minLow = " ";
  var minUpp = " ";
  var minNum = " ";
  var minSpec = " ";



  var functionArray = {
    ranLowNum : function () {
      return String.fromCharCode(Math.floor(Math.random() * 26) + 97);
    },
    
    ranUppNum : function() {
      return String.fromCharCode(Math.floor(Math.random() * 26) + 65);
    },
    
    ranNumb : function() {
      return String.fromCharCode(Math.floor(Math.random() * 10) + 48);
    },
    
    ranSpecSymbol : function() {
      const specSymbol =  "!#$%&'()*+,-./:;<=>?@[^_`{|}~";
      return symbols[Math.floor(Math.random() * specSymbol.length)];
    }
  };
 
  if (lowPass){
    minLow = functionArray.ranLowNum();
    //adding random lower case numbers to the min variable 
    min++;
  }
  if (uppPass) {
    minUpp = functionArray.ranUppNum();
    min++;
  }
  if (numPass) {
    minNum = functionArray.ranNumb();
    min++;
  }
  if (specPass) {
    minSpec = functionArray.ranSpecSymbol();
    min++;
  }

  var ranPass = "";

  for (let i = 0; i < (parseInt(passLength) - min); i++) {
    var ranGenNum = Math.floor(Math.random() * 4);
     ranPass += ranGenNum;

  }

  ranPass += minLow;
  ranPass += minUpp;
  ranPass += minNum;
  ranPass += minSpec;


  return ranPass;

}







